### ISSUE TITLE
Nightly playground

### ISSUE THREAD

**Issue by mlutze** [flix/play.flix.dev#2]
Would be nice to have a playground for the latest nightly release so that we could link directly to some problematic code in tickets.
Bonus points for being able to select an arbitrary release.

**Comment by magnus-madsen** [comment]
I like it! I will look into it.

**Comment by magnus-madsen** [comment]
(I do plan to release a new version soon though)

**Comment by magnus-madsen** [comment]
What should the name be? nightly.flix.dev? What distinguishes this name from flix.dev/nightly where the jars are?

**Comment by mlutze** [comment]
Could it be under the play domain? i.e. `nightly.play.flix.dev`?

**Comment by magnus-madsen** [comment]
I don't think this is worth it. We can just grab the newest nightly and put it into VSCode if we want to debug something.
