### ISSUE TITLE
Add examples in a drown-down

### ISSUE THREAD

**Issue by magnus-madsen** [flix/play.flix.dev#3]
So you don't have to copy paste them from flix.dev

**Comment by magnus-madsen** [comment]
@sockmaster27 Maybe you could take a look? It is low priority.

**Comment by sockmaster27** [comment]
Drown-down?

**Comment by magnus-madsen** [comment]
If you go to flix.dev you can see there is a drop-down menu with examples. I would like something similar for play.flix.dev.

**Comment by magnus-madsen** [comment]
Here we could probably use the same script as on `flix.dev` to pull-down the examples.
