### ISSUE TITLE
Share link does not work?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/play.flix.dev#9]

**Comment by sockmaster27** [comment]
It works fine on localhost, so I'm guessing that the problem is the server that it's hosted on (nginx?) intercepts it, thinking that `play.flix.dev/PQgEEEDtQ...` wants to access a resource called `PQgEEEDtQ...` instead of `index.html`.

I don't think that I can do anything about this without having access to the server and its config.

**Comment by magnus-madsen** [comment]
But is there not a hash? That should be independent of the url.

**Comment by sockmaster27** [comment]
Maybe I'm misunderstanding the problem, but again, it seems to work fine on localhost. The problem is the 404 on the deployed site, right?

**Comment by magnus-madsen** [comment]
What I mean is; I thought the link would use the anchor tag, e.g. `play.flix.dev/#foobar`?

**Comment by magnus-madsen** [comment]
Or maybe it should be `flix.dev/q=foobar`. Something fishy is going on...

**Comment by sockmaster27** [comment]
Ah, I see it now - There's a missing `?q=` not getting prepended initially

**Comment by sockmaster27** [comment]
Is it intended that the link only reflects the exact point in time when the "Shareable Link" button is clicked, and wouldn't it in this case be more intuitive if the link was copied to clipboard or displayed in a dialog or something like that?

**Comment by magnus-madsen** [comment]
> Is it intended that the link only reflects the exact point in time when the "Shareable Link" button is clicked, and wouldn't it in this case be more intuitive if the link was copied to clipboard or displayed in a dialog or something like that?

Copy to clipboard would be nice.
